---
- name: ensure libselinux-python is installed
  yum:
    name: libselinux-python
    state: present
  tags: selinux

- name: ensure policycoreutils-python is installed
  yum:
    name: policycoreutils-python
    state: present
  tags: selinux

- name: configure selinux policy and state
  selinux:
    conf: "{{ selinux_config|default('/etc/selinux/config') }}"
    policy: "{{ selinux_policy|default('targeted') }}"
    state: "{{ selinux_state|default('enforcing') }}"
  tags: selinux

- name: toggle selinux booleans
  seboolean:
    name: "{{ item.key }}"
    state: "{{ item.value.state|default('yes') }}"
    persistent: "{{ item.value.persistent|default('yes') }}"
  with_dict: "{{ selinux_boolean|default({}) }}"
  tags: selinux

- name: configure selinux network port definition
  seport:
    setype: "{{ item.key }}"
    ports: "{{ item.value.ports }}"
    proto: "{{ item.value.protocol|default('tcp') }}"
    state: "{{ item.value.state|default('present') }}"
  with_dict: "{{ selinux_ports|default({}) }}"
  tags: selinux

- name: configure selinux fcontext
  sefcontext:
    target: "{{ item.value.file_spec }}"
    ftype: "{{ item.value.ftype|default('a') }}"
    setype: "{{ item.value.setype }}"
    state: "{{ item.value.state }}"
  with_dict: "{{ selinux_fcontext|default({}) }}"
  tags: selinux
